[env:esp32-p4-nano]
platform = espressif32
board = esp32-p4-function-ev-board
framework = arduino

; Build options
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1

; Libraries
lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    me-no-dev/ESP Async WebServer@^1.2.3
    SPIFFS

; Monitor options
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Upload options
upload_speed = 921600

; Filesystem
board_build.filesystem = spiffs
board_build.partitions = custom_partitions.csv